---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: consul-server
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul::ui]
      - recipe[consul-template::default]
      - recipe[consul-test-helpers::consul-template]
    attributes:
      consul:
        service_mode: server
        servers: [ '192.168.33.10' ]
        serve_ui: true
        bind_interface: 'eth1'
        bind_addr: '192.168.33.10'
        client_address: '192.168.33.10'
      consul_template:
        config:
          consul: '127.0.0.1:8500'
  - name: consul-client
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.20"}]
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-test-helpers::consul-template]
      - recipe[test_template]
    attributes:
      consul:
        service_mode: client
        servers: [ '192.168.33.10' ]
        serve_ui: true
        bind_interface: 'eth1'
        bind_addr: '192.168.33.20'
        client_address: '192.168.33.20'
      consul_template:
        config:
          consul: '127.0.0.1:8500'
