---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: cserver
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[test_template::server]
    attributes:
      consul:
        servers: [ '192.168.33.10' ]
  - name: ta-api-lb
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.20"}]
    run_list:
      - recipe[test_template::tomcat_lb]
    attributes:
      consul:
        servers: [ '192.168.33.10' ]
  - name: ta-api
    driver:
      name: vagrant
      network:
        - ["private_network", {ip: "192.168.33.30"}]
    run_list:
      - recipe[test_template::tomcat]
    attributes:
      consul:
        servers: [ '192.168.33.10' ]
