name             'test_template'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures test_template'
long_description 'Installs/Configures test_template'
version          '0.1.0'

depends 'haproxy'
depends 'consul'
depends 'consul-template'
